Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  AuthServerAddr: 127.0.0.1:38380 
Database: 
  DBType: mysql
  Username: ctid
  Password: 12345678
  Host: 127.0.0.1:3306
  DBName: ctid_service
  TablePrefix: ctid_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30