definitions:
  errcode.Error:
    type: object
  model.Order:
    properties:
      cert_number:
        type: string
      cert_type:
        type: string
      checkin_time:
        type: integer
      checkout_time:
        type: integer
      created_by:
        type: string
      created_on:
        type: integer
      deleted_on:
        type: integer
      id:
        type: integer
      is_del:
        type: integer
      modified_by:
        type: string
      modified_on:
        type: integer
      phone:
        type: string
      room_number:
        type: integer
      state:
        type: integer
      user_name:
        type: string
    type: object
info:
  contact: {}
  description: CTID智能门锁小程序后台系统
  termsOfService: https://github.com/xielizyh/ctid_service
  title: CTID系统
  version: "1.0"
paths:
  /api/v1/orders:
    get:
      parameters:
      - description: 订单名称
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Order'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取多个订单
    post:
      parameters:
      - description: 订单名称
        in: body
        maxLength: 100
        minLength: 3
        name: name
        required: true
        schema:
          type: primitive
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: body
        name: state
        schema:
          type: primitive
      - description: 创建者
        in: body
        maxLength: 100
        minLength: 3
        name: created_by
        required: true
        schema:
          type: primitive
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.Order'
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 新增订单
  /api/v1/orders/{id}:
    delete:
      parameters:
      - description: 订单 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 删除订单
    put:
      parameters:
      - description: 订单 ID
        in: path
        name: id
        required: true
        type: integer
      - description: 订单名称
        in: body
        maxLength: 100
        minLength: 3
        name: name
        schema:
          type: primitive
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: body
        name: state
        schema:
          type: primitive
      - description: 修改者
        in: body
        maxLength: 100
        minLength: 3
        name: modified_by
        required: true
        schema:
          type: primitive
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            items:
              $ref: '#/definitions/model.Order'
            type: array
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 更新订单
swagger: "2.0"
